version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ElecWasteCollection.API/Dockerfile
    container_name: elecwastecollection-api-container
    ports:
      - "5000:8080" # Map cổng 5000 máy chủ (host) đến cổng 8080 trong container
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - /root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys # Nếu có cần volume cho Data Protection keys
